spring:
  application:
    name: todolist-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistDB
    username: user
    password: sapassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080